project 'BOF.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BOF' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BOF

  target 'BOFTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BOFUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
