project 'BOF.xcodeproj'

platform :ios, '9.0'

target 'BOF' do

  use_frameworks!

  pod 'ThunderCats', '~> 2.1'
  pod 'SkyFloatingLabelTextField', '~> 2.0'
  pod 'M13ProgressSuite', '~> 1.2'
  pod 'PureLayout', '~> 3.0'
  pod 'RMDateSelectionViewController'
  pod 'FaveButton', '~> 2.0.3'
  pod 'UICKeyChainStore'

  target 'BOFTests' do
    inherit! :search_paths
  end

  target 'BOFUITests' do
    inherit! :search_paths
    pod 'KIF', '~> 3.0'
  end

end
